# DO NOT edit this file. It will be overwritten in the grading system with a new customers_database

customers_database = {
    "customer-1": "AX-123",
    "customer-2": "BX-123",
    "customer-3": "CX-123",
    "customer-4": "DX-123",
    "customer-5": "EX-123",
}
cost_per_hour = 2


class ParkingEvent:

    def __init__(self, event_type, car_number, timestamp):
        self.event_type = event_type
        self.car_number = car_number
        self.timestamp = timestamp


class BillingEvent:

    def __init__(self, customer_id, car_number, entry_time, exit_time, parking_cost):
        self.customer_id = customer_id
        self.car_number = car_number
        self.entry_time = entry_time
        self.exit_time = exit_time
        self.parking_cost = parking_cost
